### ISSUE TITLE
Renaming `useSimple` hook

### ISSUE THREAD

**Issue by GrzegorzWidla** [Jahans3/use-simple-state#1]
I find `useSimple` to be a bit undescriptive name for this function.  
Have you considered renaming it to `useSimpleReducer`?

Consider a scenario where developer spots this hook in use and is not familiar with the library. `useSimple` does not convey anything and they'll have to dig further by checking the import definition. `useSimpleReducer` however is similar enough to native React's `useReducer` and makes it much simpler to instinctively know how to utilize the library.

If you believe that would be a valuable change I'm happy to make necessary changes in the code and documentation and submit the PR.

**Comment by Jahans3** [comment]
You make a valid point, and I'd be happy to change the name if we find something more suitable, though I think calling it a reducer is a bit of a misnomer in this case.

`useSimpleState` is descriptive, but too verbose IMO. Something along those lines would be good. Thoughts?

**Comment by GrzegorzWidla** [comment]
I think `useSimpleState` is perfectly fine and not too verbose at all.

**Comment by Jahans3** [comment]
I'm going to leave this issue open for the time being and see how people get on with `useSimple`. Will return here once hooks are fully released and this library comes out of beta :)

**Comment by Jahans3** [comment]
Renamed to `useSimpleState`, thanks for the suggestion to rename it to something more clear @GrzegorzWidla !
