### ISSUE TITLE
shouldComponentUpdate seemly return wrong result

### ISSUE THREAD

**Issue by zhangpanweb** [Jahans3/use-simple-state#10]
In `ConnectState`, when `shallowCompare` return false, which means prevState is not shalllowly equal to nextState, `shouldComponentUpdate` should return true. So the right code seem to be:
```javascript
  shouldComponentUpdate(nextProps, nextState) {
    return !shallowCompare(this.state, nextState);
  }
```

**Comment by Jahans3** [comment]
Thanks for this. Fixed and released: https://github.com/Jahans3/use-simple-state/commit/b50dfbeb018c3f55b3ef8e6e01f3fddc755af21a
